//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "UITabBarController.h"

//#import "MFMailComposeViewControllerDelegate.h"
//#import "UITabBarControllerDelegate.h"

@class NSString;

@interface MainTabBarController : UITabBarController


- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (void)daemonConnectionDied:(id)arg1;
- (void)no_nfcd_connection:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (id)init;
- (void)viewDidLayoutSubviews;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;



@end

