//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class IDTextField, NFNdefMessage, NSString, UIButton, UILabel, UITextView, UIView;

@interface EmulationViewController : UIViewController <UITextFieldDelegate>
{
    UILabel *setUIDLabel;
    UIButton *setLengthButton;
    IDTextField *textField;
    int IDLength;
    UIView *buttonView;
    UITextView *noteView;
    UITextView *noteView2;
    UILabel *buttonViewLabel;
    UILabel *notificationsLabel;
    UIView *chooseNDEFView;
    UILabel *chooseNDEFViewLabel;
    UITextView *notifView;
    NFNdefMessage *_emulationNDEFMessage;
}

+ (id)sharedInstance;
- (id)title;
- (void)showPickLength;
- (void)setUIDLength:(int)arg1 reset:(_Bool)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)setButtonEnabled:(_Bool)arg1;
- (void)buttonTapped:(id)arg1;
- (void)hostSessionDidEnd:(id)arg1;
- (void)hostSessionDidStart:(id)arg1;
- (void)chooseFromSaved:(id)arg1;
- (void)setNewUID:(id)arg1;
- (void)emulationDataWrite:(id)arg1;
- (void)emulationDataRead:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)emulationNDEFMessage;
- (void)setEmulationNDEFMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

