//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UITextField, UIView;

@interface EMVAuthController : UIViewController
{
    UILabel *topLabel;
    UILabel *lastDigitsLabel;
    UITextField *lastDigitsField;
    UIView *buttonView;
    UILabel *buttonViewLabel;
}

- (void)buttonTapped:(id)arg1;
- (void)setTempErrorText:(id)arg1;
- (void)dismissViewControllerAppearing;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (_Bool)textFieldShouldReturn:(id)arg1;

@end

