//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UILabel, UITextField;

@interface LimTransferLicenseController : PSViewController <UITextFieldDelegate>
{
    UILabel *titleLabel;
    UILabel *titleLabel2;
    UITextField *textField;
    UITextField *textField2;
}

@property(retain, nonatomic) UITextField *textField2; // @synthesize textField2;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField;
@property(retain, nonatomic) UILabel *titleLabel2; // @synthesize titleLabel2;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel;
- (id)title;
- (void)dealloc;
- (void)loadView;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)cancelAndCleanup;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

