//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIDatePicker, UILabel, UITextField, UIView;

@interface MRTDAuthController : UIViewController
{
    UILabel *topLabel;
    UILabel *docNumLabel;
    UILabel *DOELabel;
    UILabel *DOBLabel;
    UITextField *docNumField;
    UITextField *DOEField;
    UITextField *DOBField;
    UIView *buttonView;
    UILabel *buttonViewLabel;
    UIDatePicker *DOBDatePicker;
    UIDatePicker *DOEDatePicker;
}

- (void)dismissViewControllerAppearing;
- (void)buttonTapped:(id)arg1;
- (void)setTempErrorText:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)datePickerValueChanged:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

