//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "UIApplicationDelegate.h"

@class MainTabBarController, NSString, UIWindow;

@interface NFCWriterApplication : UIApplication <UIApplicationDelegate>
{
    UIWindow *_window;
    MainTabBarController *_viewController;
}

@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (void)applicationDidFinishLaunching:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

