//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BlurredLabel, NSDictionary, NSString, UIImage, UIImageView, UILabel, UIView;

@interface RoundedCell : UITableViewCell
{
    UIView *roundedBackground;
    BlurredLabel *ccNumberLabel;
    UILabel *ccExpDateLabel;
    UILabel *ccCardName;
    UILabel *ccHolderLabel;
    UIImageView *ccNameImageView;
    UILabel *expInfoLabel;
    UILabel *debitLabel;
    UILabel *bankLabel;
    UIImageView *MRTDImageView;
    _Bool selectedForCopy;
    _Bool isTransactionCell;
    _Bool isTransactionsHeader;
    _Bool isAddRecordCell;
    _Bool isAssignNDEFCell;
    NSDictionary *ccInfoDict;
    NSString *bgColorString;
    UIImage *MRTDPhoto;
    NSString *actionString;
}

@property(retain, nonatomic) NSString *actionString; // @synthesize actionString;
@property(retain, nonatomic) UIImage *MRTDPhoto; // @synthesize MRTDPhoto;
@property(nonatomic) _Bool isAssignNDEFCell; // @synthesize isAssignNDEFCell;
@property(nonatomic) _Bool isAddRecordCell; // @synthesize isAddRecordCell;
@property(nonatomic) _Bool isTransactionsHeader; // @synthesize isTransactionsHeader;
@property(nonatomic) _Bool isTransactionCell; // @synthesize isTransactionCell;
@property(retain, nonatomic) NSString *bgColorString; // @synthesize bgColorString;
@property(retain, nonatomic) NSDictionary *ccInfoDict; // @synthesize ccInfoDict;
- (void)dealloc;
- (void)layoutSubviews;
- (id)roundedBackground;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

