//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextViewDelegate.h"

@class NSString, PSSpecifier, UILabel, UITextView;

@interface ShowRecordViewController : UIViewController <UITextViewDelegate>
{
    UITextView *dataLabelField;
    UIViewController *parentv;
    PSSpecifier *_specifier;
    UILabel *typeLabel;
    UILabel *dataLabel;
    UILabel *typeLabelField;
}

- (void)deleteRecord;
- (void)viewDidLoad;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (id)specifier;
- (id)initWithSpecifier:(id)arg1 parent:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

