//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PSSpecifier, UILabel, UITextField, UITextView;

@interface ShowTagViewController : UIViewController
{
    UITextView *dataLabelField;
    UILabel *nameLabel;
    UITextField *nameField;
    UILabel *UIDLabel;
    PSSpecifier *_specifier;
    UIViewController *parentv;
}

- (void)updateTag;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)viewDidLoad;
- (void)boldifyText:(id)arg1 inTextView:(id)arg2;
- (void)deleteTag;
- (id)title;
- (id)specifier;
- (id)initWithSpecifier:(id)arg1 parent:(id)arg2;
- (void)dealloc;

@end

