//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RecordViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UILabel, UITextField;

@interface WIFIRecordViewController : RecordViewController <UITextFieldDelegate>
{
    UITextField *SSIDField;
    UITextField *PASSWORDField;
    UITextField *AUTHTYPEField;
    UITextField *ENCRYPTIONField;
    UILabel *SSIDLabel;
    UILabel *PASSWORDLabel;
    UILabel *AUTHTYPELabel;
    UILabel *ENCRYPTIONLabel;
    UIButton *button;
}

- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)addRecord:(id)arg1;
- (id)constructPayloadFromWFADictionary:(id)arg1;
- (id)title;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

