//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RecordViewController.h"

@class UIButton, UILabel, UITextField;

@interface AddContactRecordViewController : RecordViewController
{
    UILabel *nameLabel;
    UILabel *surnameLabel;
    UILabel *numberLabel;
    UITextField *nameField;
    UITextField *surnameField;
    UITextField *numberField;
    UIButton *button;
}

- (id)title;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)addRecord:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;

@end

