//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@interface DiscoverMapViewController : PSListController
{
    _Bool T1T;
    _Bool T2T;
    _Bool T3T;
    _Bool ISODEP;
    _Bool NFCDEP;
    _Bool MIFARE;
    _Bool NFC_A;
    _Bool NFC_B;
    _Bool NFC_F;
    _Bool NFC_15693;
    _Bool NFCA_KOVIO;
}

@property(nonatomic) _Bool NFCA_KOVIO; // @synthesize NFCA_KOVIO;
@property(nonatomic) _Bool NFC_15693; // @synthesize NFC_15693;
@property(nonatomic) _Bool NFC_F; // @synthesize NFC_F;
@property(nonatomic) _Bool NFC_B; // @synthesize NFC_B;
@property(nonatomic) _Bool NFC_A; // @synthesize NFC_A;
@property(nonatomic) _Bool MIFARE; // @synthesize MIFARE;
@property(nonatomic) _Bool NFCDEP; // @synthesize NFCDEP;
@property(nonatomic) _Bool ISODEP; // @synthesize ISODEP;
@property(nonatomic) _Bool T3T; // @synthesize T3T;
@property(nonatomic) _Bool T2T; // @synthesize T2T;
@property(nonatomic) _Bool T1T; // @synthesize T1T;
- (void)resetDiscoverMap:(id)arg1;
- (void)applyActivationModes:(id)arg1;
- (void)resetActivationModes:(id)arg1;
- (void)applyDiscoverableProtocols:(id)arg1;
- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
- (id)readPreferenceValue:(id)arg1;
- (id)specifiers;

@end

