//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ManageRecordsViewController.h"

@class UILabel;

@interface ManageTagsViewController : ManageRecordsViewController
{
    UILabel *_headerLabel;
    _Bool isUIDHelper;
}

- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)clearAllRecords;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(id)arg2;
- (id)specifiers;
- (void)dismissMe:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initForEmulationUID;
- (void)_setEditable:(_Bool)arg1 animated:(_Bool)arg2;

@end

