//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, UIImageView, UILabel, UITextField, UITextView, UIToolbar, UIView;

@interface NFCClientController : UIViewController <UITextFieldDelegate, UITextViewDelegate>
{
    UILabel *topLabel;
    UILabel *infoLabel;
    UIView *buttonView;
    UILabel *buttonViewLabel;
    UIImageView *tagView;
    UITextField *portField;
    UILabel *portLabel;
    UITextField *ipField;
    UILabel *ipLabel;
    UITextView *logView;
    UIToolbar *numberToolbar;
    UIToolbar *ipNumberToolbar;
}

- (void)buttonTapped:(id)arg1;
- (void)clientStopped:(id)arg1;
- (void)clientStarted:(id)arg1;
- (void)clientUpdated:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)portNumberPadDone:(id)arg1;
- (void)ipNumberPadDone:(id)arg1;
- (void)loadView;
- (id)init;
- (void)clientDataWrite:(id)arg1;
- (void)clientDataRead:(id)arg1;
- (id)title;
- (id)topLabelText;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

