//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, UIImageView, UILabel, UITextField, UITextView, UIToolbar, UIView;

@interface NFCServerController : UIViewController <UITextFieldDelegate, UITextViewDelegate>
{
    UILabel *topLabel;
    UILabel *infoLabel;
    UIView *buttonView;
    UILabel *buttonViewLabel;
    UIImageView *tagView;
    NSString *publicIP;
    UITextField *portField;
    UILabel *portLabel;
    UITextView *logView;
    UIToolbar *numberToolbar;
    UILabel *bottomLabel;
}

- (id)title;
- (void)buttonTapped:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)numberPadDone:(id)arg1;
- (void)loadView;
- (void)setTopLabelText:(id)arg1;
- (void)serverStopped:(id)arg1;
- (void)serverStarted:(id)arg1;
- (void)serverStarting:(id)arg1;
- (id)localIPAddress;
- (void)serverObtainedPublicIP:(id)arg1;
- (void)viewableDataChanged:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

