//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSMutableString, UITextView;

@interface NFCWriterTransmissionLogViewController : UIViewController
{
    NSMutableString *_log;
    UITextView *textView;
}

- (void)share:(id)arg1;
- (void)loadView;
- (void)dismissActiveViewController;
- (id)initWithTransmissionLog:(id)arg1;

@end

