//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CNContactViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UIImageView, UILabel, UITableView, UITextView, UIView, _UIBackdropView;

@interface ReaderViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, CNContactViewControllerDelegate>
{
    UILabel *headerLabel;
    UILabel *tagIDHeader;
    UILabel *tagIDLabel;
    UILabel *typeLabel;
    UILabel *actionLabel;
    UILabel *typeTitleLabel;
    UILabel *ndefTitleLabel;
    UITextView *ndefLabel;
    UIImageView *v;
    UIView *roundedRect;
    UIView *roundedRect2;
    UIView *roundedRect3;
    UIView *button;
    UITableView *_tableView;
    NSDictionary *tagsFoundDict;
    NSMutableArray *tableArray;
    UIImageView *tableHeaderOverlay;
    UIImageView *tableFooterOverlay;
    _Bool isAnimatingMoveTag;
    UILabel *_moveTagLabel;
    UILabel *welcomeLabel1;
    UILabel *welcomeLabel2;
    _UIBackdropView *uiback;
    UILabel *infoLabel;
    UIView *_emvNotifyView;
    UIView *_mrtdNotifyView;
    UIView *_desfireNotifyView;
    UIView *_moveCardView;
    UIView *buttonView;
    UILabel *buttonViewLabel;
    UIView *messagesView;
    UILabel *messagesLabel1;
    UILabel *messagesLabel2;
}

- (void)EMVPayCardNeedsVerification:(id)arg1;
- (void)mrtdDataMissing:(id)arg1;
- (void)buttonTapped:(id)arg1;
- (void)tagReaderFinished:(id)arg1;
- (void)setScrollingText:(id)arg1;
- (void)viewDidLoad;
- (void)tagReaderFailedContinuously:(id)arg1;
- (void)showMoveTagMessage:(id)arg1;
- (void)reportNFCDCrash;
- (void)NFCD_RESPONSE:(id)arg1;
- (void)foundMRTDDataStatus:(id)arg1;
- (void)MRTDMessage:(id)arg1;
- (void)foundMRTDDataEnd:(id)arg1;
- (void)foundMRTDDataStart:(id)arg1;
- (void)foundEMVDataEnd:(id)arg1;
- (void)foundEMVDataStart:(id)arg1;
- (void)foundDesfireDataEnd:(id)arg1;
- (void)foundDesfireDataStart:(id)arg1;
- (void)tagNeedsMoving:(id)arg1;
- (id)mrtdNotifyView;
- (id)moveCardView;
- (id)desfireNotifyView;
- (id)emvNotifyView;
- (void)cellTextCopied:(id)arg1;
- (void)sameTagDetected:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)showTableView;
- (void)hideTableView;
- (void)didDetectTagsWithInfo:(id)arg1;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)openTransmissionLog:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)start;
- (void)gotSelected;
- (void)handleActionsForRecordsInDict:(id)arg1;
- (id)constructDictionaryFromWFAData:(id)arg1;
- (void)dismissViewControllerAppearing;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

