//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class UILabel, UIView;

@interface SettingsController : PSListController
{
    UIView *_NFCWriterXHeaderView;
    UILabel *_versionLabel;
    UILabel *_showOffLabel;
}

+ (id)sharedInstance;
- (id)title;
- (void)viewDidAppear:(_Bool)arg1;
- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
- (id)specifiers;
- (void)restartNFCD:(id)arg1;
- (void)loadView;
- (void)viewDidLayoutSubviews;

@end

