//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RecordViewController.h"

@class UIButton, UILabel, UITextField;

@interface URIRecordViewController : RecordViewController
{
    int selectedIndex;
    UILabel *prefixLabel;
    UITextField *uriField;
    UIButton *button;
}

- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)changePrefix;
- (void)setPrefix:(id)arg1;
- (void)viewDidLoad;
- (void)addRecord:(id)arg1;
- (id)title;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;

@end

